[default]
description = "Default permissions for the app"
permissions = ["allow-app-commands"]

[[permission]]
identifier = "allow-app-commands"
description = "Enables all app commands"
commands.allow = [
    "load_doc",
    "store_update",
    "record_patch",
    "list_patches",
    "get_patch",
    "detect_conflicts",
    "get_conflicts",
    "resolve_conflict",
    "get_conflict_count",
    "get_profile",
    "save_profile",
    "get_profile_path",
    "export_kmd",
    "import_kmd",
    "export_markdown",
    "export_docx",
    "get_document_meta",
    "set_document_title",
    "write_text_file",
    "new_document",
    "open_document",
    "save_document",
    "close_document",
    "get_open_documents",
    "get_recent_documents",
    "clear_recent_documents",
    "set_active_document",
    "get_active_document",
    "get_document_state",
    "update_document_state",
    "mark_document_modified",
    "update_document_title",
    "record_document_patch",
    "list_document_patches",
    "get_initial_file",
    "save_document_snapshot",
    "restore_document_to_patch",
    "update_patch_review_status",
    "import_patches_from_document",
    "reset_imported_patches_status",
    "save_snapshot",
    "get_snapshot_for_patch",
    "restore_to_patch",
    "add_comment",
    "list_comments",
    "add_reply",
    "resolve_comment",
    "delete_comment",
    "mark_comment_deleted",
    "restore_comment"
]
